# Generated by Django 6.0 on 2025-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=125)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('pdf', models.FileField(null=True, upload_to='pdf')),
                ('date_ajout', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
